#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# Every path below is relative to the repo root, so anchor there.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

PORT=4242
DUMP_SERVER="scripts/dump-server.mjs"
mkdir -p tmp   # runtime artifacts (logs, captures) stay gitignored
NGROK_BIN="${NGROK_BIN:-ngrok}"

# json_field FILE PATH: pull a dotted path out of a JSON file using node,
# which this repo already depends on, so no jq requirement.
json_field() {
  node -e '
    const fs = require("fs");
    const doc = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    const value = process.argv[2].split(".").reduce((o, k) => o?.[k], doc);
    process.stdout.write(value == null ? "" : String(value));
  ' "$1" "$2" 2>/dev/null || true
}

banner "PayMongo webhook tunnel setup"

# ── Stage 1: ngrok account and authtoken ──────────────────────────────────
stage "ngrok: account and authtoken"
say "ngrok gives the dev machine a public HTTPS URL. PayMongo will not accept"
say "a webhook endpoint that isn't publicly reachable over HTTPS."

if ! command -v "$NGROK_BIN" >/dev/null 2>&1; then
  warn "ngrok isn't on PATH. Install it, then re-run this wizard."
  exit 1
fi

if "$NGROK_BIN" config check >/dev/null 2>&1 && \
   grep -qs 'authtoken' "$HOME/.config/ngrok/ngrok.yml"; then
  note "an authtoken is already configured on this machine"
  if ! confirm "Replace it?"; then
    say "keeping the existing authtoken"
  else
    NGROK_AUTHTOKEN=""
  fi
fi

if [[ "${NGROK_AUTHTOKEN-unset}" != "unset" ]] || \
   ! grep -qs 'authtoken' "$HOME/.config/ngrok/ngrok.yml"; then
  open_url "https://dashboard.ngrok.com/signup"
  step "Sign up (or log in). GitHub and Google SSO both work. The free plan is enough."
  pause "Signed in? Press Enter."
  open_url "https://dashboard.ngrok.com/get-started/your-authtoken"
  step "Copy the authtoken shown on this page."
  ask_secret NGROK_AUTHTOKEN "Paste your ngrok authtoken:"
  if [[ -z "$NGROK_AUTHTOKEN" ]]; then
    warn "no authtoken given; cannot continue"
    exit 1
  fi
  "$NGROK_BIN" config add-authtoken "$NGROK_AUTHTOKEN" >/dev/null
  printf '  %s✓ saved%s authtoken to ngrok config\n' "$GREEN" "$RESET"
fi
pause

# ── Stage 2: the assigned dev domain ──────────────────────────────────────
stage "ngrok: assigned dev domain"
say "The free plan includes one assigned domain that survives restarts."
say "A stable URL matters: the POC pays real money once, then replays that"
say "webhook delivery forever, and a rotating URL would put that at risk."
open_url "https://dashboard.ngrok.com/domains"
step "Copy your assigned domain. It looks like: something-1234.ngrok-free.app"
note "If the list is empty, create one — the free plan allows exactly one."
ask NGROK_DOMAIN "Paste the domain (no https://):"
NGROK_DOMAIN="${NGROK_DOMAIN#https://}"
NGROK_DOMAIN="${NGROK_DOMAIN#http://}"
NGROK_DOMAIN="${NGROK_DOMAIN%/}"
if [[ -z "$NGROK_DOMAIN" ]]; then
  warn "no domain given; cannot continue"
  exit 1
fi
write_env NGROK_DOMAIN "$NGROK_DOMAIN"
PAYMONGO_WEBHOOK_URL="https://${NGROK_DOMAIN}/webhook"
write_env PAYMONGO_WEBHOOK_URL "$PAYMONGO_WEBHOOK_URL"
pause

# ── Stage 3: stand up the tunnel and prove a request round-trips ──────────
stage "Tunnel: start and verify"
say "Starting the request-dump handler and the tunnel, then sending a request"
say "the long way round — through the public URL — to prove it lands locally."

if curl -sf -o /dev/null "http://localhost:${PORT}/" -X POST -d '{}' 2>/dev/null; then
  note "dump server already listening on ${PORT}"
else
  step "starting $DUMP_SERVER on port ${PORT}"
  PORT="$PORT" node "$DUMP_SERVER" > tmp/dump-server.log 2>&1 &
  sleep 2
fi

if curl -sf -o /dev/null "http://127.0.0.1:4040/api/tunnels" 2>/dev/null; then
  note "an ngrok agent is already running; leaving it alone"
else
  step "starting ngrok on https://${NGROK_DOMAIN}"
  "$NGROK_BIN" http "$PORT" --url "https://${NGROK_DOMAIN}" --log stdout \
    > tmp/ngrok.log 2>&1 &
  sleep 4
fi

step "sending a probe through https://${NGROK_DOMAIN}/webhook"
PROBE_FILE=$(mktemp)
PROBE_ERR=$(mktemp)
PROBE_OK=""

if curl -sS -m 20 -o "$PROBE_FILE" -X POST "https://${NGROK_DOMAIN}/webhook" \
     -H 'Content-Type: application/json' -d '{"probe":"wizard"}' 2>"$PROBE_ERR" && \
   grep -q '"received"' "$PROBE_FILE"; then
  PROBE_OK=1
elif grep -qi 'could not resolve host' "$PROBE_ERR"; then
  # This machine's resolver can't see the ngrok zone (common under WSL, where
  # the Windows NAT DNS proxy filters ngrok-free.app). It does NOT affect
  # PayMongo, which resolves the domain from its own network. Re-probe over
  # DNS-over-HTTPS so the round-trip can still be proven locally.
  warn "local DNS can't resolve ${NGROK_DOMAIN}; retrying via DNS-over-HTTPS"
  PROBE_IP=$(curl -sS -m 10 \
    "https://1.1.1.1/dns-query?name=${NGROK_DOMAIN}&type=A" \
    -H 'accept: application/dns-json' 2>/dev/null | node -e '
      let s = "";
      process.stdin.on("data", (d) => (s += d)).on("end", () => {
        const answers = (JSON.parse(s || "{}").Answer ?? []).filter((a) => a.type === 1);
        process.stdout.write(answers.length ? answers[0].data : "");
      });
    ' 2>/dev/null || true)
  if [[ -n "$PROBE_IP" ]] && \
     curl -sS -m 20 -o "$PROBE_FILE" -X POST \
       --resolve "${NGROK_DOMAIN}:443:${PROBE_IP}" \
       "https://${NGROK_DOMAIN}/webhook" \
       -H 'Content-Type: application/json' -d '{"probe":"wizard"}' 2>"$PROBE_ERR" && \
     grep -q '"received"' "$PROBE_FILE"; then
    PROBE_OK=1
    note "resolved ${NGROK_DOMAIN} to ${PROBE_IP} out of band"
    warn "fix local DNS before you rely on curling this URL by hand:"
    note "  sudo tee /etc/resolv.conf <<< 'nameserver 1.1.1.1'"
    note "  and set [network] generateResolvConf=false in /etc/wsl.conf to persist it"
  fi
fi

if [[ -n "$PROBE_OK" ]]; then
  printf '  %s✓ round-trip confirmed%s — the tunnel reaches the local handler\n' "$GREEN" "$RESET"
else
  warn "the probe did not come back as expected."
  note "curl said: $(head -c 300 "$PROBE_ERR" 2>/dev/null || echo '(nothing)')"
  note "body was:  $(head -c 300 "$PROBE_FILE" 2>/dev/null || echo '(nothing)')"
  note "check tmp/ngrok.log and tmp/dump-server.log"
  if ! confirm "Continue anyway?"; then exit 1; fi
fi
rm -f "$PROBE_FILE" "$PROBE_ERR"
note "leave this tunnel running: PayMongo delivers to it"
pause

# ── Stage 4: register the webhook endpoint with PayMongo ──────────────────
stage "PayMongo: register the webhook endpoint"
warn "This writes to your LIVE PayMongo account."
say "Live is forced, not chosen: the in-store QR exists only under the live key."
say "Registering an endpoint moves no money by itself."
note "Endpoint: ${PAYMONGO_WEBHOOK_URL}"
note "Events:   qr.paid, payment.paid"

set -a; . ./.env; set +a
if [[ -z "${PAYMONGO_SECRET_KEY_LIVE:-}" || "$PAYMONGO_SECRET_KEY_LIVE" == "sk_live_" ]]; then
  warn "PAYMONGO_SECRET_KEY_LIVE is missing from .env; cannot register"
  exit 1
fi

step "listing endpoints already registered on this account"
EXISTING=$(mktemp)
curl -sS -u "${PAYMONGO_SECRET_KEY_LIVE}:" https://api.paymongo.com/v1/webhooks > "$EXISTING"
node -e '
  const fs = require("fs");
  const list = JSON.parse(fs.readFileSync(process.argv[1], "utf8")).data ?? [];
  if (!list.length) { console.log("    (none registered)"); }
  for (const w of list) {
    console.log(`    ${w.id}  ${w.attributes.status}  ${w.attributes.url}`);
  }
' "$EXISTING" || note "  (could not parse the endpoint list)"
rm -f "$EXISTING"

if ! confirm "Register ${PAYMONGO_WEBHOOK_URL} now?"; then
  SKIPPED+=("PayMongo webhook registration")
  finish
  exit 0
fi

RESPONSE=$(mktemp)
curl -sS -u "${PAYMONGO_SECRET_KEY_LIVE}:" https://api.paymongo.com/v1/webhooks \
  -H 'Content-Type: application/json' \
  -d "$(node -e '
    process.stdout.write(JSON.stringify({
      data: { attributes: { url: process.argv[1], events: ["qr.paid", "payment.paid"] } },
    }));
  ' "$PAYMONGO_WEBHOOK_URL")" > "$RESPONSE"

WEBHOOK_ID=$(json_field "$RESPONSE" "data.id")
WEBHOOK_SECRET=$(json_field "$RESPONSE" "data.attributes.secret_key")

if [[ -z "$WEBHOOK_ID" ]]; then
  warn "registration failed. PayMongo said:"
  note "$(head -c 600 "$RESPONSE")"
  rm -f "$RESPONSE"
  exit 1
fi
rm -f "$RESPONSE"

write_env PAYMONGO_WEBHOOK_ID "$WEBHOOK_ID"
write_env PAYMONGO_WEBHOOK_SECRET_KEY "$WEBHOOK_SECRET"
note "the secret signs the Paymongo-Signature header; verify against the RAW body"
pause

finish
say "Next: make the ₱1 QR Ph payment, then check tmp/captures/ for the delivery."
printf '\n'
